server:
  port: 8080

spring:
  application:
    name: Lidar Api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: luxoft
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

lidar:
  data-file-path: "src/main/resources/files/lidar_case.data"
  idx-file-path: "src/main/resources/files/lidar_case.data.idx"
  files-base-path: "src/main/resources/files/"

openapi:
  title: "Lidar API"
  description: "Lidar data processing application"
  version: "v1.0"
  license:
    name: "Apache 2.0"
    url: "http://springdoc.org"
